# CMake generated Testfile for 
# Source directory: /home/mamccord/ggml/tests
# Build directory: /home/mamccord/ggml/build_gpu/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test-mul-mat2 "/home/mamccord/ggml/build_gpu/bin/test-mul-mat2")
set_tests_properties(test-mul-mat2 PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-mul-mat2.profraw" _BACKTRACE_TRIPLES "/home/mamccord/ggml/tests/CMakeLists.txt;213;add_test;/home/mamccord/ggml/tests/CMakeLists.txt;0;")
add_test(test0 "/home/mamccord/ggml/build_gpu/bin/test0")
set_tests_properties(test0 PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test0.profraw" _BACKTRACE_TRIPLES "/home/mamccord/ggml/tests/CMakeLists.txt;226;add_test;/home/mamccord/ggml/tests/CMakeLists.txt;0;")
add_test(test-backend-ops "/home/mamccord/ggml/build_gpu/bin/test-backend-ops")
set_tests_properties(test-backend-ops PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-backend-ops.profraw" _BACKTRACE_TRIPLES "/home/mamccord/ggml/tests/CMakeLists.txt;246;add_test;/home/mamccord/ggml/tests/CMakeLists.txt;0;")
add_test(test-opt "/home/mamccord/ggml/build_gpu/bin/test-opt")
set_tests_properties(test-opt PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-opt.profraw" _BACKTRACE_TRIPLES "/home/mamccord/ggml/tests/CMakeLists.txt;256;add_test;/home/mamccord/ggml/tests/CMakeLists.txt;0;")
add_test(test-quantize-fns "/home/mamccord/ggml/build_gpu/bin/test-quantize-fns")
set_tests_properties(test-quantize-fns PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-quantize-fns.profraw" _BACKTRACE_TRIPLES "/home/mamccord/ggml/tests/CMakeLists.txt;265;add_test;/home/mamccord/ggml/tests/CMakeLists.txt;0;")
add_test(test-quantize-perf "/home/mamccord/ggml/build_gpu/bin/test-quantize-perf")
set_tests_properties(test-quantize-perf PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-quantize-perf.profraw" _BACKTRACE_TRIPLES "/home/mamccord/ggml/tests/CMakeLists.txt;274;add_test;/home/mamccord/ggml/tests/CMakeLists.txt;0;")
add_test(test-mul-mat0 "/home/mamccord/ggml/build_gpu/bin/test-mul-mat0")
set_tests_properties(test-mul-mat0 PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-mul-mat0.profraw" _BACKTRACE_TRIPLES "/home/mamccord/ggml/tests/CMakeLists.txt;287;add_test;/home/mamccord/ggml/tests/CMakeLists.txt;0;")
add_test(test-pool "/home/mamccord/ggml/build_gpu/bin/test-pool")
set_tests_properties(test-pool PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-pool.profraw" _BACKTRACE_TRIPLES "/home/mamccord/ggml/tests/CMakeLists.txt;299;add_test;/home/mamccord/ggml/tests/CMakeLists.txt;0;")
add_test(test-arange "/home/mamccord/ggml/build_gpu/bin/test-arange")
set_tests_properties(test-arange PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-arange.profraw" _BACKTRACE_TRIPLES "/home/mamccord/ggml/tests/CMakeLists.txt;311;add_test;/home/mamccord/ggml/tests/CMakeLists.txt;0;")
add_test(test-timestep_embedding "/home/mamccord/ggml/build_gpu/bin/test-timestep_embedding")
set_tests_properties(test-timestep_embedding PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-timestep_embedding.profraw" _BACKTRACE_TRIPLES "/home/mamccord/ggml/tests/CMakeLists.txt;323;add_test;/home/mamccord/ggml/tests/CMakeLists.txt;0;")
add_test(test-pad-reflect-1d "/home/mamccord/ggml/build_gpu/bin/test-pad-reflect-1d")
set_tests_properties(test-pad-reflect-1d PROPERTIES  _BACKTRACE_TRIPLES "/home/mamccord/ggml/tests/CMakeLists.txt;332;add_test;/home/mamccord/ggml/tests/CMakeLists.txt;0;")
add_test(test-conv-transpose "/home/mamccord/ggml/build_gpu/bin/test-conv-transpose")
set_tests_properties(test-conv-transpose PROPERTIES  _BACKTRACE_TRIPLES "/home/mamccord/ggml/tests/CMakeLists.txt;340;add_test;/home/mamccord/ggml/tests/CMakeLists.txt;0;")
add_test(test-conv-transpose-1d "/home/mamccord/ggml/build_gpu/bin/test-conv-transpose-1d")
set_tests_properties(test-conv-transpose-1d PROPERTIES  _BACKTRACE_TRIPLES "/home/mamccord/ggml/tests/CMakeLists.txt;347;add_test;/home/mamccord/ggml/tests/CMakeLists.txt;0;")
add_test(test-dup "/home/mamccord/ggml/build_gpu/bin/test-dup")
set_tests_properties(test-dup PROPERTIES  _BACKTRACE_TRIPLES "/home/mamccord/ggml/tests/CMakeLists.txt;355;add_test;/home/mamccord/ggml/tests/CMakeLists.txt;0;")
add_test(test-rel-pos "/home/mamccord/ggml/build_gpu/bin/test-rel-pos")
set_tests_properties(test-rel-pos PROPERTIES  _BACKTRACE_TRIPLES "/home/mamccord/ggml/tests/CMakeLists.txt;363;add_test;/home/mamccord/ggml/tests/CMakeLists.txt;0;")
add_test(test-customop "/home/mamccord/ggml/build_gpu/bin/test-customop")
set_tests_properties(test-customop PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-customop.profraw" _BACKTRACE_TRIPLES "/home/mamccord/ggml/tests/CMakeLists.txt;374;add_test;/home/mamccord/ggml/tests/CMakeLists.txt;0;")
add_test(test-conv1d "/home/mamccord/ggml/build_gpu/bin/test-conv1d")
set_tests_properties(test-conv1d PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-conv1d.profraw" _BACKTRACE_TRIPLES "/home/mamccord/ggml/tests/CMakeLists.txt;383;add_test;/home/mamccord/ggml/tests/CMakeLists.txt;0;")
add_test(test-conv2d "/home/mamccord/ggml/build_gpu/bin/test-conv2d")
set_tests_properties(test-conv2d PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-conv2d.profraw" _BACKTRACE_TRIPLES "/home/mamccord/ggml/tests/CMakeLists.txt;393;add_test;/home/mamccord/ggml/tests/CMakeLists.txt;0;")
add_test(test-conv2d-dw "/home/mamccord/ggml/build_gpu/bin/test-conv2d-dw")
set_tests_properties(test-conv2d-dw PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-conv2d-dw.profraw" _BACKTRACE_TRIPLES "/home/mamccord/ggml/tests/CMakeLists.txt;403;add_test;/home/mamccord/ggml/tests/CMakeLists.txt;0;")
add_test(test-mul-mat "/home/mamccord/ggml/build_gpu/bin/test-mul-mat")
set_tests_properties(test-mul-mat PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-mul-mat.profraw" _BACKTRACE_TRIPLES "/home/mamccord/ggml/tests/CMakeLists.txt;413;add_test;/home/mamccord/ggml/tests/CMakeLists.txt;0;")
add_test(test-cont "/home/mamccord/ggml/build_gpu/bin/test-cont")
set_tests_properties(test-cont PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-cont.profraw" _BACKTRACE_TRIPLES "/home/mamccord/ggml/tests/CMakeLists.txt;422;add_test;/home/mamccord/ggml/tests/CMakeLists.txt;0;")
add_test(test-mul-mat-hsa "/home/mamccord/ggml/build_gpu/bin/test-mul-mat-hsa")
set_tests_properties(test-mul-mat-hsa PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=test-mul-mat-hsa.profraw" _BACKTRACE_TRIPLES "/home/mamccord/ggml/tests/CMakeLists.txt;431;add_test;/home/mamccord/ggml/tests/CMakeLists.txt;0;")
